apiVersion: v1
kind: Pod
metadata:
 name: android
 labels:
   app: android
spec:
 containers:
 - name: android
   image: budtmo/docker-android-x86-8.0
   securityContext:
     privileged: true
   ports:
     - name: android-vnc
       containerPort: 6080
     - name: android-console
       containerPort: 5554
     - name: android-adb
       containerPort: 5555
     - name: android-appium
       containerPort: 4723
   resources:
     requests:
       memory: "2048Mi"
       cpu: "2000m"
     limits:
       memory: "4192Mi"
       cpu: "4000m"
