apiVersion: v1
kind: Service
metadata:
 name: android
spec:
 type: NodePort
 ports:
   - name: android-vnc
     port: 6080
     nodePort: 30680
   - name: android-console
     port: 5554
     nodePort: 30554
   - name: android-adb
     port: 5555
     nodePort: 30555
   - name: android-appium
     port: 4723
     nodePort: 30723
 selector:
   app: android
